import * as fs from "node:fs";
import * as path from "node:path";
import * as vscode from "vscode";

const LOAD_SCENE_DECL_HEADER = `// Generated by GameIDE — do not edit.

`;

function isIdentifier(key: string): boolean {
  return /^[$A-Z_a-z][$\w]*$/.test(key);
}

function formatObjectKey(key: string): string {
  return isIdentifier(key) ? key : JSON.stringify(key);
}

function formatLiteralType(value: unknown, depth = 0): string {
  const indent = "  ".repeat(depth);
  const childIndent = "  ".repeat(depth + 1);

  if (Array.isArray(value)) {
    if (value.length === 0) return "readonly []";
    return `readonly [\n${value
      .map((item) => `${childIndent}${formatLiteralType(item, depth + 1)}`)
      .join(",\n")}\n${indent}]`;
  }

  if (value === null) return "null";

  switch (typeof value) {
    case "string":
      return JSON.stringify(value);
    case "number":
      return Number.isFinite(value) ? String(value) : "number";
    case "boolean":
      return value ? "true" : "false";
    case "object": {
      const entries = Object.entries(value as Record<string, unknown>);
      if (entries.length === 0) return "{}";
      return `{\n${entries
        .map(
          ([key, child]) =>
            `${childIndent}readonly ${formatObjectKey(key)}: ${formatLiteralType(child, depth + 1)};`
        )
        .join("\n")}\n${indent}}`;
    }
    default:
      return "unknown";
  }
}

function sceneKey(workspaceRootFsPath: string, sceneFsPath: string): string {
  return path.relative(workspaceRootFsPath, sceneFsPath).split(path.sep).join("/");
}

function generateSceneTypesGenTs(workspaceRootFsPath: string, sceneFsPaths: string[]): string {
  if (sceneFsPaths.length === 0) {
    return `${LOAD_SCENE_DECL_HEADER}export type GameIDEScenes = Record<string, never>;
`;
  }

  const typeLines = sceneFsPaths.map((scenePath) => {
    const raw = fs.readFileSync(scenePath, "utf8");
    const data = JSON.parse(raw) as unknown;
    const k = sceneKey(workspaceRootFsPath, scenePath);
    return `  readonly ${JSON.stringify(k)}: ${formatLiteralType(data)};`;
  });

  return `${LOAD_SCENE_DECL_HEADER}export type GameIDEScenes = {
${typeLines.join("\n")}
};
`;
}

function generateGameideSceneDts(): string {
  return `${LOAD_SCENE_DECL_HEADER}declare module "*.scene" {
  const data: import("./sceneTypes.gen").GameIDEScenes[keyof import("./sceneTypes.gen").GameIDEScenes];
  export default data;
}
`;
}

async function writeGameideSceneDeclarations(workspaceFolder: vscode.WorkspaceFolder): Promise<void> {
  const root = workspaceFolder.uri.fsPath;
  const pattern = new vscode.RelativePattern(workspaceFolder, "**/*.scene");
  const sceneUris = await vscode.workspace.findFiles(pattern, "**/node_modules/**");
  const sceneFsPaths = sceneUris.map((u) => u.fsPath).sort();
  const outDir = path.join(root, ".gameide");
  await vscode.workspace.fs.createDirectory(vscode.Uri.file(outDir));

  const legacyVirtual = path.join(outDir, "virtual-gameide-scenes.d.ts");
  try {
    await vscode.workspace.fs.delete(vscode.Uri.file(legacyVirtual));
  } catch {
    // ignore if absent
  }

  const genPath = path.join(outDir, "sceneTypes.gen.ts");
  const dtsPath = path.join(outDir, "gameide-scene.d.ts");
  const genContent = generateSceneTypesGenTs(root, sceneFsPaths);
  const dtsContent = generateGameideSceneDts();

  async function writeIfChanged(filePath: string, body: string): Promise<void> {
    const uri = vscode.Uri.file(filePath);
    const nextBytes = Buffer.from(body, "utf8");
    let current: Buffer | undefined;
    try {
      current = Buffer.from(await vscode.workspace.fs.readFile(uri));
    } catch {
      current = undefined;
    }
    if (current && current.equals(nextBytes)) return;
    await vscode.workspace.fs.writeFile(uri, nextBytes);
  }

  await writeIfChanged(genPath, genContent);
  await writeIfChanged(dtsPath, dtsContent);
}

export async function syncSceneDeclaration(sceneUri: vscode.Uri): Promise<void> {
  const folder = vscode.workspace.getWorkspaceFolder(sceneUri);
  if (!folder) return;
  await writeGameideSceneDeclarations(folder);
}

export async function deleteSceneDeclaration(sceneUri: vscode.Uri): Promise<void> {
  const folder = vscode.workspace.getWorkspaceFolder(sceneUri);
  if (!folder) return;
  await writeGameideSceneDeclarations(folder);
}

export async function syncAllSceneDeclarations(): Promise<void> {
  await Promise.allSettled(
    (vscode.workspace.workspaceFolders ?? []).map((folder) =>
      writeGameideSceneDeclarations(folder)
    )
  );
}

function assetKey(workspaceRootFsPath: string, assetFsPath: string): string {
  return path.relative(workspaceRootFsPath, assetFsPath).split(path.sep).join("/");
}

function generateVirtualGameIDEAssetsDts(workspaceRootFsPath: string, assetFsPaths: string[]): string {
  if (assetFsPaths.length === 0) {
    return `${LOAD_SCENE_DECL_HEADER}declare module "virtual:gameide-assets" {
  export type GameIDEAssets = { readonly importPath: string };
  export function loadAssets(): GameIDEAssets;
}
`;
  }

  const typeLines = assetFsPaths.map((assetPath) => {
    const k = assetKey(workspaceRootFsPath, assetPath);
    return `    readonly ${JSON.stringify(k)}: string;`;
  });

  return `${LOAD_SCENE_DECL_HEADER}declare module "virtual:gameide-assets" {
  export type GameIDEAssets = {
    readonly importPath: string;
${typeLines.join("\n")}
  };
  export function loadAssets(): GameIDEAssets;
}
`;
}

async function writeVirtualGameIDEAssetsDeclaration(
  workspaceFolder: vscode.WorkspaceFolder
): Promise<void> {
  const root = workspaceFolder.uri.fsPath;
  const pattern = new vscode.RelativePattern(workspaceFolder, "assets/**");
  const assetUris = await vscode.workspace.findFiles(
    pattern,
    "**/{node_modules,.git,dist}/**"
  );
  const assetFsPaths = assetUris
    .map((u) => u.fsPath)
    .filter((p) => {
      try {
        return fs.statSync(p).isFile();
      } catch {
        return false;
      }
    })
    .sort();
  const content = generateVirtualGameIDEAssetsDts(root, assetFsPaths);
  const outPath = path.join(root, ".gameide", "virtual-gameide-assets.d.ts");
  const outDir = path.dirname(outPath);
  await vscode.workspace.fs.createDirectory(vscode.Uri.file(outDir));
  const uri = vscode.Uri.file(outPath);
  const nextBytes = Buffer.from(content, "utf8");
  let current: Buffer | undefined;
  try {
    current = Buffer.from(await vscode.workspace.fs.readFile(uri));
  } catch {
    current = undefined;
  }
  if (current && current.equals(nextBytes)) return;
  await vscode.workspace.fs.writeFile(uri, nextBytes);
}

export async function syncAssetDeclaration(assetUri: vscode.Uri): Promise<void> {
  const folder = vscode.workspace.getWorkspaceFolder(assetUri);
  if (!folder) return;
  await writeVirtualGameIDEAssetsDeclaration(folder);
}

export async function deleteAssetDeclaration(assetUri: vscode.Uri): Promise<void> {
  const folder = vscode.workspace.getWorkspaceFolder(assetUri);
  if (!folder) return;
  await writeVirtualGameIDEAssetsDeclaration(folder);
}

export async function syncAllAssetsDeclarations(): Promise<void> {
  await Promise.allSettled(
    (vscode.workspace.workspaceFolders ?? []).map((folder) =>
      writeVirtualGameIDEAssetsDeclaration(folder)
    )
  );
}
