import type { Plugin, ResolvedConfig, ViteDevServer } from "vite";
import { normalizePath } from "vite";
import fs from "node:fs";
import path from "node:path";
import type { GameIDEMetadata } from "./meta/gameideManifestTypes.js";

const MANIFEST_VIRTUAL = "\0virtual:gameide-manifest";
const SCENES_VIRTUAL = "\0virtual:gameide-scenes";
const ASSETS_VIRTUAL = "\0virtual:gameide-assets";

const SKIP_DIR_NAMES = new Set([".gameide", ".git", "dist", "node_modules"]);

type JsonPrimitive = string | number | boolean | null;
type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };

function readManifestData(root: string): GameIDEMetadata {
  const manifestPath = path.join(root, "gameide.json");
  if (!fs.existsSync(manifestPath)) {
    return {};
  }
  try {
    const raw = fs.readFileSync(manifestPath, "utf8");
    return JSON.parse(raw) as GameIDEMetadata;
  } catch {
    return {};
  }
}

function loadManifestModuleSource(root: string): string {
  const data = readManifestData(root);
  return `export default ${JSON.stringify(data)};\n`;
}

function parseSceneJson(raw: string): JsonValue {
  return JSON.parse(raw) as JsonValue;
}

function createSceneModuleCode(data: JsonValue): string {
  return `const data = ${JSON.stringify(data)};
export default data;
`;
}

function isIdentifier(key: string): boolean {
  return /^[$A-Z_a-z][$\w]*$/.test(key);
}

function formatObjectKey(key: string): string {
  return isIdentifier(key) ? key : JSON.stringify(key);
}

function formatLiteralType(value: JsonValue, depth = 0): string {
  const indent = "  ".repeat(depth);
  const childIndent = "  ".repeat(depth + 1);

  if (Array.isArray(value)) {
    if (value.length === 0) return "readonly []";
    return `readonly [\n${value
      .map((item) => `${childIndent}${formatLiteralType(item, depth + 1)}`)
      .join(",\n")}\n${indent}]`;
  }

  if (value === null) return "null";

  switch (typeof value) {
    case "string":
      return JSON.stringify(value);
    case "number":
      return Number.isFinite(value) ? String(value) : "number";
    case "boolean":
      return value ? "true" : "false";
    case "object": {
      const entries = Object.entries(value as { [key: string]: JsonValue });
      if (entries.length === 0) return "{}";
      return `{\n${entries
        .map(
          ([key, child]) =>
            `${childIndent}readonly ${formatObjectKey(key)}: ${formatLiteralType(child, depth + 1)};`
        )
        .join("\n")}\n${indent}}`;
    }
    default:
      return "unknown";
  }
}

function ensureParentDirectory(filePath: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function writeIfChanged(filePath: string, content: string): void {
  const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : undefined;
  if (existing === content) return;
  ensureParentDirectory(filePath);
  fs.writeFileSync(filePath, content);
}

function listSceneFiles(scanDir: string): string[] {
  const out: string[] = [];

  function walk(dir: string): void {
    if (!fs.existsSync(dir)) return;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (SKIP_DIR_NAMES.has(entry.name)) continue;

      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath);
        continue;
      }
      if (entry.isFile() && fullPath.endsWith(".scene")) {
        out.push(fullPath);
      }
    }
  }

  walk(scanDir);
  out.sort();
  return out;
}

function listAssetFiles(assetsDir: string): string[] {
  if (!fs.existsSync(assetsDir)) return [];
  const out: string[] = [];

  function walk(dir: string): void {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (SKIP_DIR_NAMES.has(entry.name)) continue;
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath);
        continue;
      }
      if (entry.isFile()) {
        out.push(fullPath);
      }
    }
  }

  walk(assetsDir);
  out.sort();
  return out;
}

function sceneKey(rootDir: string, scenePath: string): string {
  return normalizePath(path.relative(rootDir, scenePath));
}

function generateLoadScenesModule(rootDir: string, scenePaths: string[]): string {
  if (scenePaths.length === 0) {
    return `export function loadScenes() {
  return {};
}
`;
  }

  const imports = scenePaths.map(
    (p, i) => `import _gide_scene${i} from ${JSON.stringify(normalizePath(p))};`
  );
  const keys = scenePaths.map((p) => sceneKey(rootDir, p));
  const objLines = keys.map((k, i) => `    ${JSON.stringify(k)}: _gide_scene${i},`);

  return `${imports.join("\n")}

export function loadScenes() {
  return {
${objLines.join("\n")}
  };
}
`;
}

const LOAD_ASSETS_DECL_HEADER = `// Generated by GameIDE vite plugin — do not edit.

`;

function generateLoadAssetsModule(rootDir: string, assetPaths: string[]): string {
  if (assetPaths.length === 0) {
    return `export function loadAssets() {
  return {};
}
`;
  }

  const imports = assetPaths.map(
    (p, i) => `import _gide_asset${i} from ${JSON.stringify(`${normalizePath(p)}?url`)};`
  );
  const keys = assetPaths.map((p) => sceneKey(rootDir, p));
  const objLines = keys.map((k, i) => `    ${JSON.stringify(k)}: _gide_asset${i},`);

  return `${imports.join("\n")}

export function loadAssets() {
  return {
${objLines.join("\n")}
  };
}
`;
}

function generateLoadAssetsDeclarationFile(rootDir: string, assetPaths: string[]): string {
  if (assetPaths.length === 0) {
    return `${LOAD_ASSETS_DECL_HEADER}declare module "virtual:gameide-assets" {
  export type GameIDEAssets = Record<string, never>;
  export function loadAssets(): GameIDEAssets;
}
`;
  }

  const typeLines = assetPaths.map((p) => {
    const k = sceneKey(rootDir, p);
    return `    readonly ${JSON.stringify(k)}: string;`;
  });

  return `${LOAD_ASSETS_DECL_HEADER}declare module "virtual:gameide-assets" {
  export type GameIDEAssets = {
${typeLines.join("\n")}
  };
  export function loadAssets(): GameIDEAssets;
}
`;
}

function syncLoadAssetsDeclaration(rootDir: string): void {
  const assetsDir = path.join(rootDir, "assets");
  const paths = listAssetFiles(assetsDir);
  const declPath = path.join(rootDir, ".gameide", "virtual-gameide-assets.d.ts");
  writeIfChanged(declPath, generateLoadAssetsDeclarationFile(rootDir, paths));
}

const LOAD_SCENE_DECL_HEADER = `// Generated by GameIDE vite plugin — do not edit.

`;

function generateLoadScenesDeclarationFile(rootDir: string, scenePaths: string[]): string {
  if (scenePaths.length === 0) {
    return `${LOAD_SCENE_DECL_HEADER}declare module "virtual:gameide-scenes" {
  export type GameIDEScenes = Record<string, never>;
  export function loadScenes(): GameIDEScenes;
}
`;
  }

  const typeLines = scenePaths.map((p) => {
    const raw = fs.readFileSync(p, "utf8");
    const data = parseSceneJson(raw);
    const k = sceneKey(rootDir, p);
    return `    readonly ${JSON.stringify(k)}: ${formatLiteralType(data)};`;
  });

  return `${LOAD_SCENE_DECL_HEADER}declare module "virtual:gameide-scenes" {
  export type GameIDEScenes = {
${typeLines.join("\n")}
  };
  export function loadScenes(): GameIDEScenes;
}
`;
}

function syncLoadScenesDeclaration(rootDir: string): void {
  const paths = listSceneFiles(rootDir);
  const declPath = path.join(rootDir, ".gameide", "virtual-gameide-scenes.d.ts");
  writeIfChanged(declPath, generateLoadScenesDeclarationFile(rootDir, paths));
  const legacyTypesRoot = path.join(rootDir, ".gameide-types");
  if (fs.existsSync(legacyTypesRoot)) {
    fs.rmSync(legacyTypesRoot, { recursive: true, force: true });
  }
}

function isUnderProjectAssets(rootDir: string, changedPath: string): boolean {
  const assetsRoot = path.join(rootDir, "assets");
  const rel = path.relative(path.resolve(assetsRoot), path.resolve(changedPath));
  return rel !== ".." && !rel.startsWith(`..${path.sep}`) && !path.isAbsolute(rel);
}

function syncSceneDeclarationsInDirectory(rootDir: string): void {
  syncLoadScenesDeclaration(rootDir);
  syncLoadAssetsDeclaration(rootDir);
}

function invalidateVirtualModule(server: ViteDevServer, virtualId: string): void {
  const mod = server.moduleGraph.getModuleById(virtualId);
  if (mod) server.moduleGraph.invalidateModule(mod);
}

export function gameidePlugin(): Plugin {
  let config: ResolvedConfig | undefined;

  return {
    name: "gameide-plugin",
    configResolved(resolvedConfig) {
      config = resolvedConfig;
      syncSceneDeclarationsInDirectory(config.root);
    },
    configureServer(server) {
      const manifestPath = path.join(server.config.root, "gameide.json");
      server.watcher.add(manifestPath);

      const onMaybeSceneTreeChange = (changedPath: string): void => {
        if (!changedPath.endsWith(".scene")) return;
        if (!config) return;
        syncSceneDeclarationsInDirectory(config.root);
        invalidateVirtualModule(server, SCENES_VIRTUAL);
      };

      const onMaybeAssetTreeChange = (changedPath: string): void => {
        if (!config) return;
        if (!isUnderProjectAssets(config.root, changedPath)) return;
        syncLoadAssetsDeclaration(config.root);
        invalidateVirtualModule(server, ASSETS_VIRTUAL);
      };

      const assetsPath = path.join(server.config.root, "assets");
      if (fs.existsSync(assetsPath)) {
        server.watcher.add(assetsPath);
      }

      server.watcher.on("change", (changedPath) => {
        if (path.normalize(changedPath) === path.normalize(manifestPath)) {
          invalidateVirtualModule(server, MANIFEST_VIRTUAL);
          return;
        }
        onMaybeSceneTreeChange(changedPath);
        onMaybeAssetTreeChange(changedPath);
      });
      server.watcher.on("add", (changedPath) => {
        onMaybeSceneTreeChange(changedPath);
        onMaybeAssetTreeChange(changedPath);
      });
      server.watcher.on("unlink", (changedPath) => {
        onMaybeSceneTreeChange(changedPath);
        onMaybeAssetTreeChange(changedPath);
      });
    },
    buildStart() {
      if (!config) return;
      syncSceneDeclarationsInDirectory(config.root);
    },
    resolveId(id: string) {
      if (id === "virtual:gameide-manifest") {
        return MANIFEST_VIRTUAL;
      }
      if (id === "virtual:gameide-scenes") {
        return SCENES_VIRTUAL;
      }
      if (id === "virtual:gameide-assets") {
        return ASSETS_VIRTUAL;
      }
      return;
    },
    load(id: string) {
      if (id === MANIFEST_VIRTUAL) {
        const root = config?.root;
        if (!root) {
          return "export default {};\n";
        }
        return loadManifestModuleSource(root);
      }
      if (id === SCENES_VIRTUAL) {
        const root = config?.root;
        if (!root) {
          return `export function loadScenes() {
  return {};
}
`;
        }
        const paths = listSceneFiles(root);
        syncLoadScenesDeclaration(root);
        return generateLoadScenesModule(root, paths);
      }
      if (id === ASSETS_VIRTUAL) {
        const root = config?.root;
        if (!root) {
          return `export function loadAssets() {
  return {};
}
`;
        }
        const assetsDir = path.join(root, "assets");
        const paths = listAssetFiles(assetsDir);
        syncLoadAssetsDeclaration(root);
        return generateLoadAssetsModule(root, paths);
      }
      const cleanId = id.replace(/\?.*$/, "");
      if (!cleanId.endsWith(".scene")) return;
      if (config) syncLoadScenesDeclaration(config.root);
      const raw = fs.readFileSync(cleanId, "utf8");
      const data = parseSceneJson(raw);
      return createSceneModuleCode(data);
    },
    watchChange(id: string) {
      if (!config) return;
      if (id.endsWith(".scene")) {
        syncLoadScenesDeclaration(config.root);
      }
      if (isUnderProjectAssets(config.root, id)) {
        syncLoadAssetsDeclaration(config.root);
      }
    },
  };
}
